r0gue-io/pop-cli

src/commands/build/contract.rs
src/commands/build/mod.rs
src/commands/new/contract.rs
src/commands/new/mod.rs
src/commands/new/pallet.rs
src/commands/new/parachain.rs
src/commands/test/contract.rs
src/commands/test/mod.rs
src/commands/up/contract.rs
src/commands/up/mod.rs
src/engines/contract_engine.rs
src/main.rs

Various fixes and tweaks to improve ux.

refactor: improve ux

---

Cargo.toml
README.md

Updates language in docs: the tool is creating something _from_ templates, rather than creating templates which are embedded within the tool.
Also aligned the package description with the readme intro.

docs: update readme

---

Cargo.toml
src/engines/contract_engine.rs

error when `cargo install --path .`

fix: update dependencies

---

Cargo.lock

https://github.com/r0gue-io/pop-cli/pull/48

Fix: build error on main 

---

.github/workflows/build.yml
src/commands/new/contract.rs
src/engines/contract_engine.rs
src/engines/parachain_engine.rs
tests/build_contract.rs

This will add the `cargo fmt` check to our CI

chore: add `cargo fmt` check

---

README.md

closes https://github.com/r0gue-io/pop-cli/issues/93

add cargo contract acknowledgement

---

src/commands/new/parachain.rs
src/engines/templates.rs
src/git.rs
src/helpers.rs

An additional observation is that the OZ release does not include a zombienet config file as it appears in their main branch, so we should probably just download a copy manually to show the full flow.

refactor: various improvements

---

Cargo.lock
Cargo.toml

bump contract-build to 4.0.2

---

.github/workflows/release.yml
Cargo.lock
Cargo.toml
crates/pop-cli/Cargo.toml

release: create a release for pop-cli

---

.github/workflows/build.yml
crates/pop-cli/src/main.rs
crates/pop-cli/src/style.rs

Only builds with required features when performing integration tests.

ci: use features when testing

---

crates/pop-cli/src/main.rs

Telemetry would parse and use two args: command and subcommand. Before `pop install` all commands were guaranteed to have at least 3 arguments. However, `pop install` does not have a subcommand, and hence additional checks were needed to handle only 2 arguments.

fix: invalid .expect when parsing args with intro of pop install command

---

README.md

Fix a broken link that closes https://github.com/r0gue-io/pop-cli/issues/192

fix: readme link to the documentation

---

crates/pop-cli/src/commands/new/contract.rs
crates/pop-cli/src/commands/new/parachain.rs

Further improves the consitency between the new contract and parachain commands.

refactor: improve new consistency

---

crates/pop-cli/src/commands/call/contract.rs
crates/pop-cli/src/commands/up/contract.rs

Ensures consistent with the behaviour in `pop up contract` and simplifies devex with one less parameter to specify.

refactor: default suri

---

crates/pop-cli/src/commands/test/contract.rs
crates/pop-cli/src/common/contracts.rs
crates/pop-common/src/sourcing/binary.rs

Some minor improvements and a fix.

refactor: e2e test improvements

---

Cargo.lock
Cargo.toml
crates/pop-cli/src/commands/build/spec.rs
crates/pop-parachains/README.md
crates/pop-parachains/src/build.rs
crates/pop-parachains/src/errors.rs
crates/pop-parachains/src/lib.rs

Refactors to use serde_json for replacement of existing chain spec values.

refactor(chain-spec): json replacement

---

README.md

docs: add community section to README

---

crates/pop-cli/src/commands/build/spec.rs

While including the info logs was an easy fix to get rid of some poor handling of the spinner, this achieves the same end goal.

fix(spec): better handling of spinner

---

Cargo.toml
crates/pop-cli/src/commands/build/mod.rs
crates/pop-cli/src/commands/build/parachain.rs
crates/pop-cli/src/commands/build/spec.rs
crates/pop-common/Cargo.toml
crates/pop-common/src/build.rs
crates/pop-common/src/manifest.rs
crates/pop-parachains/src/build.rs

These are changes done by Daan addressing some feedback and doing further improvements after the rebase.

chore: feedback and rebase

---

crates/pop-cli/src/commands/call/contract.rs
crates/pop-cli/src/commands/call/parachain.rs
crates/pop-common/src/metadata.rs
crates/pop-parachains/src/call/metadata/action.rs
crates/pop-parachains/src/call/metadata/mod.rs
crates/pop-parachains/src/call/metadata/params.rs
crates/pop-parachains/src/call/mod.rs
crates/pop-parachains/src/errors.rs

Simply PR to resolve conflicts from the [feat-call-ui-extrinsics-limited](https://github.com/r0gue-io/pop-cli/tree/feat-call-ui-extrinsics-limited) branch, and fix the PR accordingly to your changes.
Probably only things that matter for your review is where you made changes, in:
- [crates/pop-cli/src/commands/call/parachain.rs](https://github.com/r0gue-io/pop-cli/compare/daan/refactor-structs...alex/fix-conflicts?expand=1#diff-2a362fc04a86bb35dc59d686099bf6119504e74e29c61c1b7aa18a3a6cf2b4f9)
- https://github.com/r0gue-io/pop-cli/compare/daan/refactor-structs...alex/fix-conflicts?expand=1#diff-042140c03e18a5880d4dd545ad1f7c9be962ce76f1002744d3a6243bc2f503d7
The rest are only changes coming from [feat-call-ui-extrinsics-limited](https://github.com/r0gue-io/pop-cli/tree/feat-call-ui-extrinsic …

fix: solve conflicts and unit tests

---

crates/pop-cli/src/commands/call/parachain.rs
crates/pop-parachains/src/call/metadata/action.rs
crates/pop-parachains/src/call/metadata/mod.rs
crates/pop-parachains/src/call/metadata/params.rs
crates/pop-parachains/src/call/mod.rs

Various fixes and improvements to `pop call parachain`.

refactor: various fixes and improvements

---

crates/pop-cli/src/commands/call/parachain.rs
crates/pop-common/src/build.rs
crates/pop-common/src/lib.rs
crates/pop-common/src/signer.rs
crates/pop-parachains/src/call/metadata/mod.rs
crates/pop-parachains/src/call/metadata/params.rs
crates/pop-parachains/src/call/mod.rs

Various fixes and improvements.

refactor: improvements

---

crates/pop-cli/src/commands/bench/pallet.rs

Guide user to select profile before building the runtime.

feat: add select profile in pallet benchmarking

---

.github/actions/init/action.yml
.github/workflows/ci.yml
crates/pop-cli/Cargo.toml

- Cleaned up CI pipeline to resolve "no space left on device" issue
- Removed redundant unit test execution (already covered in the coverage step)
- Added execution of PolkaVM contract unit tests

fix: clean ci

---

.github/workflows/ci.yml
README.md
crates/pop-cli/src/commands/mod.rs
crates/pop-cli/src/commands/new/mod.rs
crates/pop-cli/src/commands/test/mod.rs
crates/pop-cli/src/commands/up/mod.rs
crates/pop-cli/src/commands/up/network.rs
crates/pop-cli/src/common/contracts.rs
crates/pop-cli/src/main.rs
crates/pop-common/src/errors.rs
crates/pop-common/src/git.rs
crates/pop-common/src/lib.rs
crates/pop-common/src/polkadot_sdk.rs
crates/pop-common/src/sourcing/mod.rs
crates/pop-common/src/templates/mod.rs
crates/pop-contracts/README.md
crates/pop-contracts/src/new.rs
crates/pop-contracts/src/templates.rs
crates/pop-parachains/src/bench/mod.rs
crates/pop-parachains/src/errors.rs
crates/pop-parachains/src/lib.rs
crates/pop-parachains/src/new_pallet/new_pallet_options.rs
crates/pop-parachains/src/templates.rs
crates/pop-telemetry/README.md
crates/pop-telemetry/src/lib.rs

Addresses all issues reported by `cargo doc` and then also adds missing docs for public items.
[sc-3576]

docs: improve project documentation

---

crates/pop-common/src/api.rs

Resolves the https://rust-lang.github.io/rust-clippy/master/index.html#await_holding_lock clippy warning.

refactor(common/api): use async-aware mutex

---

.github/CODEOWNERS
.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/docker-ci.yml
.github/workflows/install.yml
.gitignore
Cargo.lock
crates/pop-chains/Cargo.toml
crates/pop-chains/tests/chain.rs
crates/pop-chains/tests/metadata.rs
crates/pop-cli/Cargo.toml
crates/pop-cli/src/commands/test/create_snapshot.rs
crates/pop-cli/src/commands/test/execute_block.rs
crates/pop-cli/src/common/binary.rs
crates/pop-cli/tests/chain.rs
crates/pop-cli/tests/contract.rs
crates/pop-common/Cargo.toml
crates/pop-common/tests/metadata.rs
crates/pop-contracts/Cargo.toml
crates/pop-contracts/tests/contracts.rs

This PR:
- Allows to specify the rust version when building the docker image. This way if we change the rust version in `rust-toolchain.toml` a new docker image will be created to run everything.
- Gathers integration tests in a single feature. Integration tests should not count for the coverage.
- Fixes a few conflictive tests.
- Skips install checks if relevant source files not modified.

ci: several improvements
