r0gue-io/pop-cli

.gitignore, Cargo.lock, Cargo.toml, src/commands/build/contract.rs, src/engines/contract_engine.rs
Closes: https://github.com/r0gue-io/pop-cli/issues/21
With this PR output will be as follows:
```
┌   Pop CLI : Building a contract
│
[==] Checking clippy linting rules
Finished dev [unoptimized + debuginfo] target(s) in 0.13s
[==] Building cargo project
Finished release [optimized] target(s) in 0.08s
◆  
│  The contract was built in RELEASE mode.
│  
│  Your contract artifacts are ready. You can find them in:
│  /Users/bruno/src/pop-cli/my_contract/target/ink
│  
│    - my_contract.contract (code + metadata)
│    - my_contract.wasm (the contract's code)
│    - my_contract.json (the contract's metadata)
│  
└  Build completed successfully!
```
=> feat: pop build contract: add build output

src/engines/generator.rs, src/engines/parachain_engine.rs, src/helpers.rs, templates/base/network.templ
Adds simple network config file, so that parachain can easily be launched with the following after build:
```shell
pop up parachain -f ./network.toml
```
closes #39
=> feat(new-parachain): add network config

templates/base/network.templ
Tried to keep config light to be mindful of user's resources, but actually running a local network results in `[Relaychain] failed to calculate erasure root para_id=1000 err=Erasure(NotEnoughValidators)`.
Adding another validator resolves.
=> feat(new-parachain): increase validators

templates/base/runtime-cargo.templ, templates/base/runtime.templ
The idea is to not have the `pallet_template` in the` base-parachain `and add it using pop-cli `pop add pallet`.
Goes with this PR in `base-parachain` node: https://github.com/r0gue-io/base-parachain/pull/5
=> refactor: remove `pallet_template` from parachain template

.dockerignore, Cargo.lock, Cargo.toml, Dockerfile, src/commands/up/parachain.rs, src/parachains/zombienet.rs, tests/zombienet.toml
Improves command handling and legacy zombienet flle support by:
- automatically adding zombinetnet-sdk `settings` to temp config when not specified
- defaulting to `polkadot` for relay, `polkadot-parachain` for parachain when not specified
- resolves `default_command` and `command` to local binaries when relative paths specified
- simplifies test `zombienet.toml` file
Closes #25
=> fix(up-parachain): improve command handling

Cargo.lock, Cargo.toml, src/engines/contract_engine.rs, src/engines/parachain_engine.rs
As per https://crates.io/crates/tempdir, tempdir was deprecated ages ago with functionality moved into tempfile which already exists as a dependency. Primary motivation was a security advisory triggered by dependabot: https://github.com/r0gue-io/pop-cli/security/dependabot/1.
=> fix(deps): remove deprecated dependency

.github/workflows/build.yml, src/commands/new/parachain.rs, src/helpers.rs
This PR solves for #61. It initializes a new git repo with `initialized parachain` as the commit message. It takes the default global user config from git and uses it as the signature. 
Currently the test passes even if there is no `.git` dir in the new parachain. I need help with that.
=> feat: init git repo

src/engines/contract_engine.rs
Add unit test for `pop test contract`.
=> test: add unit test for `pop test contract`

.github/workflows/build.yml, src/engines/parachain_engine.rs
Unit test for `pop build parachain`
=> test: add unit test for `pop build parachain`

Cargo.lock, Cargo.toml, src/commands/new/contract.rs, src/engines/contract_engine.rs, tests/build_contract.rs
- Added a new test on `pop new contract`
- Added unit and integration tests for `pop build contract`
=> test: pop build contract

src/engines/pallet_engine.rs, src/helpers.rs
This PR adds a unit test for `create_pallet_template`.
=> test: add unit test for `pop new pallet`

Cargo.lock, README.md, src/commands/up/mod.rs, src/commands/up/parachain.rs
Adds an optional `--verbose` or `-v` argument to the up parachain command, which includes the command that was used to launch a node in the output which can be useful in advanced scenarios.
=> feat(up-parachain): enable optional verbose output

.github/workflows/build.yml, Cargo.toml, README.md, src/engines/contract_engine.rs, src/engines/parachain_engine.rs, tests/build_contract.rs, tests/build_parachain.rs
Fixing Issue https://github.com/r0gue-io/pop-cli/issues/88
- Run only unit tests when `cargo test`
- unit tests that are a bit slower, build a contract move it into feature `unit_contract`. To run `cargo test --features unit_contract `
- Run e2e tests using a feature flag `cargo test --features e2e_contract` for contracts and `cargo test --features e2e_parachain` for parachains
- Moved the test that builds a parachain to e2e test
- In the CI run everything `cargo test --all-features -- --include-ignored`
=> fix: cargo test takes too long to test

src/commands/new/contract.rs, src/commands/new/parachain.rs, src/engines/contract_engine.rs, src/main.rs
`new parachain` does not take any `-p, --path` arguments but `new contract` does. 
We should stick to consistent messaging formats across both. 
`cd into {project_path} and enjoy hacking` should be the default, and paths should be printed only if the user invoked them with `-p, --path` 
Another inconsistency I noticed was given an arbitrary path, `a/b/c` to `new parachain` it would create folders if not present, the same is not done by `create_smart_contract`. This is now resolved and the corresponding test case has been removed as it's not needed anymore.
=> Make `pop new <contract | parachain>` consistent

Cargo.toml, src/git.rs, src/parachains/zombienet.rs
Simply uses serde to deserialise releases to improve filtering, allowing the exclusion of prereleases and filtering by tag. Adding additonal fields will be much easier in the future. Currently returns all releases to let the caller apply the filtering, as the full list is downloaded in any case. Can be further optimised in the future.
Note: will currently download `polkadot` and `polkadot-parachain` at v1.10.  `-s v1.10.1` can be specified to explictly use the latest `polkadot-parachain` version currently available.
=> refactor: improve latest release filtering

Cargo.toml, src/git.rs, src/parachains/zombienet.rs
We are fetching the latest polkadot version from https://github.com/paritytech/polkadot-sdk/releases,
Latest release there is a [Polkadot Parachain](https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-parachain-v1.10.1) release, and this was making the tool fail because we are trying to get a version of Polkadot that doesn't exist:
```
Error: error sending request for url (https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-parachain-v1.10.1/polkadot): error trying to connect: unexpected EOF
```
The workaround suggested in this PR: fetch the latest n (5 in this case) versions and iterate to find the Polkadot version.
=> fix: fetch latest polkadot releases

Cargo.lock, Cargo.toml, crates/pop-cli/src/commands/new/parachain.rs, crates/pop-parachains/Cargo.toml, crates/pop-parachains/src/new_parachain.rs, crates/pop-parachains/src/utils/git.rs
A user reported an issue when generating the parachain:
```
~/github/pop
❯ pop new parachain Demo
┌   Pop CLI : Generating "Demo" using Base Parachain Template!
│
Error: authentication required but no callback set; class=Ssh (23); code=Auth (-16)
```
It seem our current code for cloning a repository was throwing an error, fixed using `RepoBuilder`. Based on this example: https://docs.rs/git2/0.13.1/git2/build/struct.RepoBuilder.html#example 
After that fix user was having another issue:
```
~/github/pop
❯ pop new parachain my-app
┌   Pop CLI : Generating "my-app" using Base Parachain Template!
Error: remote rejected authentication: Failed getting response; class=Ssh (23); code=Auth (-16)
```
With seems is an issue authenticating for the SSH clone. Fixed using the library: …
=> fix: clone when user use ssh 

Cargo.lock, crates/pop-cli/src/commands/new/contract.rs, crates/pop-cli/src/commands/new/parachain.rs, crates/pop-cli/src/helpers.rs, crates/pop-contracts/src/new.rs, crates/pop-contracts/src/utils/helpers.rs, crates/pop-parachains/Cargo.toml, crates/pop-parachains/src/errors.rs, crates/pop-parachains/src/lib.rs, crates/pop-parachains/src/new_parachain.rs, crates/pop-parachains/src/templates.rs, crates/pop-parachains/src/utils/git.rs
Maximises the use of the `Provider` and `Template` enums so that new templates can be added easily and in a single place.
Note: I think the Parity templates should be marked as deprecated owing to how old the available releases are. We could also look to provide the default branch as an additional option to the available releases, perhaps via an opt-in flag/property by provider or template.
=> refactor: maximise use of enums

.github/workflows/release.yml, Cargo.lock, crates/pop-cli/Cargo.toml
Fixes the cross compilation issues. Results of a run at https://github.com/r0gue-io/pop-cli/actions/runs/8853101362, tested briefly on all platforms via Docker/Linux/Rosetta using Mac.
Also removed skylake as dont think we need to make that available.
=> build: enable vendored-openssl via feature to ease cross compilation

Cargo.lock, Cargo.toml, crates/pop-cli/src/commands/call/contract.rs, crates/pop-cli/src/commands/new/contract.rs, crates/pop-cli/src/commands/new/pallet.rs, crates/pop-cli/src/commands/new/parachain.rs, crates/pop-cli/src/commands/up/contract.rs, crates/pop-cli/src/commands/up/parachain.rs, crates/pop-parachains/src/lib.rs, crates/pop-parachains/src/up.rs
Improves the ux when building binaries for `pop up parachain`, by updating `cliclack` and by using a callback to pass underlying `cargo build` status updates back up to cli ui for output.
Also adds a retry attempt should the first attempt fail. This is primarily due to an interrupted process, but could potentially be due to a connectivity issue.
=> feat(up parachain): improve build ux

crates/pop-cli/src/commands/new/parachain.rs, crates/pop-cli/src/main.rs, crates/pop-parachains/src/templates.rs
Adds possible values to help output, so that it no longer needs to be statically defined.
=> feat(help): possible values

crates/pop-parachains/src/templates.rs
This PR substitutes #131.
Asset parachain template moved to: https://github.com/r0gue-io/assets-parachain
=> feat(cli): integrate assets parachain template.

crates/pop-parachains/src/templates.rs
Quick fix for a bug we introduced after a refactor in the Provider enum.
Was not getting the list of templates a provider have: 
```
Select a template provider: 
│  ● Pop (An all-in-one tool for Polkadot development. 0 available option(s) )
│  ○ Parity
```
And throwing an error when try to generate a parachain using the user guide.
Fixed and unit test added to prevent it for happening again.
=> fix: retrieve templates of provider

crates/pop-cli/src/commands/new/contract.rs, crates/pop-cli/src/commands/new/parachain.rs, crates/pop-contracts/src/build.rs, crates/pop-contracts/src/call.rs, crates/pop-contracts/src/test.rs, crates/pop-contracts/src/up.rs, crates/pop-contracts/src/utils/helpers.rs, crates/pop-parachains/src/new_pallet.rs, crates/pop-parachains/src/new_parachain.rs, crates/pop-parachains/src/up.rs
Existing implementation was not propagating errors encountered whilst running tests, making debugging when running via CI harder. All tests should now fail with the actual error encountered.
=> test: ensure errors propagated

crates/pop-parachains/src/up.rs, tests/zombienet.toml
Uses rococo para id until we can replace with paseo-local.
=> chore: update para id

crates/pop-parachains/templates/base/network.templ
Should be outside of the system parachain range.
=> fix: update para id

.github/workflows/install.yml, .github/workflows/release.yml, crates/pop-cli/Cargo.toml
Also adds a workflow for checking install of the current branch using a standard ubuntu container, which can be replicated for other flavours of Linux. The final command can then simply become `pop install` once that feature is ready.
=> build(deps): use git2 vendored-openssl feature

crates/pop-parachains/src/up.rs, crates/pop-parachains/src/utils/git.rs
Close: https://github.com/r0gue-io/pop-cli/issues/138
In `pop up parachain` we are getting the last Polkadot release from the GitHub API. If there is something wrong with this call (for example:  IP blocked by Github due to rate limit), return at least a default version
=> fix: error parsing polkadot version from github API

Cargo.lock, Cargo.toml, tests/zombienet.toml
Bumps zombienet-sdk dependency, ensure that `args` works when specified in network config.
=> build(deps): bump zombienet-sdk

crates/pop-parachains/src/templates.rs
Uses proper naming based on contracts pallet and Frontier repo readmes.
=> docs: improve descriptions

.github/workflows/ci.yml, codecov.yml
Adds code coverage checks.
Coverage report from this branch at https://app.codecov.io/gh/r0gue-io/pop-cli/tree/frank%2Fcode-coverage.
=> ci: add code coverage

crates/pop-cli/src/main.rs, crates/pop-parachains/src/generator/parachain.rs, crates/pop-parachains/src/utils/git.rs, crates/pop-parachains/src/utils/helpers.rs
Add some more unit tests to improve the coverage.
=> test: add more unit tests

crates/pop-telemetry/README.md, crates/pop-telemetry/src/lib.rs
Fixes the failing tests, whilst also ensuring that test errors are properly propagated so we can see the actual source of failure when run during CI.
Partial run at https://github.com/r0gue-io/pop-cli/actions/runs/9061239245
=> test: fix test failures

Cargo.lock, Cargo.toml, crates/pop-cli/Cargo.toml, crates/pop-contracts/Cargo.toml, crates/pop-contracts/tests/contract.rs
Bumps dependencies in order:
- address advisories
- use crates.io version of zombienet-sdk
- update contracts related dependencies to release version
Also ensures all dependencies are defined in workspace manifest.
=> build(deps): update dependencies

.github/workflows/ci.yml, Cargo.toml, deny.toml
Adds cargo-deny to CI workflow for dependency and license checks.
Note: the list of allowed licenses have not yet been validated in terms of compliance. This should be completed before this PR is accepted.
=> ci: add dependency and license checks

crates/pop-cli/src/commands/build/contract.rs, crates/pop-cli/src/commands/build/parachain.rs, crates/pop-cli/src/commands/new/parachain.rs, crates/pop-parachains/src/templates.rs
Improves post-generation UX by showing next steps for building and launching a parachain (provided a network config file exists for the template).
Also includes a link to docs.
=> feat(new): add next steps

README.md, crates/pop-cli/Cargo.toml, crates/pop-cli/src/commands/up/contracts_node.rs, crates/pop-cli/src/commands/up/mod.rs, crates/pop-cli/src/main.rs
This PR adds the following command that spawns a [substrate-contracts-node](https://github.com/paritytech/substrate-contracts-node) instance.
```sh
pop up contracts-node
```
It should be executed in a different terminal, and prior to its execution it will check whether the repository is downloaded and build the binary if it isn't.
It's definitely not rocket science, and could be improved, but IMO it's a decent step forward towards a better usage by integrating in the tool a component that was excluded, yet it was used for deploying smart contracts.
- Check whether the current version of the software is the latest, and if not force-download the latest.
- The above, but with a `--force`-like command.
- Include features when building the binary.
- Pass command-line arguments to the node for …
=> Add the "pop up contracts-node" command

crates/pop-cli/src/commands/new/parachain.rs, crates/pop-parachains/src/templates.rs, crates/pop-parachains/src/utils/git.rs
This PR introduces UX improvements to the pop new parachain command.
- Warns user if template does not have any releases
- Introduces an optional "SupportedVersions" field to the Template variants.
- Introduces an optional "IsAudited" field to the Template variants. If set to true, will hide the audit warning.
- Displays the repo license for the template
SupportedVersions is introduced as a simple way to support OpenZeppelin templates. Right now, OpenZeppelin's default branch uses a monorepo style. However, the `v1.0.0` release does not use a monorepo. By specifying the supported version, we can control the flow in a consistent way. When OpenZeppelin introduces a release with the monorepo, we will be able to use the supported versions to not support v1.0.0 and we can introduce additional …
=> feat(new): ux improvements

crates/pop-parachains/src/templates.rs
This PR adds support for the OpenZeppelin Generic Polkadot Runtime Template.
Non-audited OpenZeppelin templates are not supported. OpenZeppelin's only release is not in the monorepo format. So, any future releases will need additional changes to support the monorepo. 
Co-authored-by: Frank Bell <60948618+evilrobot-01@users.noreply.github.com>
=> feat: add OpenZeppelin template

crates/pop-parachains/src/templates.rs
Hi there!
Since the name of our repository has changed after making it a monorepo for all templates, I think updating the link here will also make sense.
=> refactor: use the new link for OZ templates after repo name changed

README.md, crates/pop-cli/src/commands/build/contract.rs, crates/pop-cli/src/commands/up/contract.rs, crates/pop-contracts/README.md, crates/pop-contracts/src/build.rs, crates/pop-contracts/src/call.rs, crates/pop-contracts/tests/contract.rs
Allow user to indicate the build mode for the contract: debug (default) or release with the flag `--release`.
Example:
```sh
pop build contract -p ./my_contract --release
```
Closes https://github.com/r0gue-io/pop-cli/issues/102
=> feat: allow user to choose build mode: debug (default) or release

crates/pop-telemetry/README.md
Documentation of crate `pop-telemetry` was using the old TG link.
=> fix: Correct TG link

Cargo.lock, crates/pop-cli/Cargo.toml, crates/pop-contracts/Cargo.toml, crates/pop-telemetry/Cargo.toml, deny.toml
1. Remove unused dependencies in different crates. Using [cargo machete](https://github.com/bnjbvr/cargo-machete) to detect unused dependencies.
2. Run `cargo update` to update to the latest [semver](https://semver.org/) compatible version.
This close the issue https://github.com/r0gue-io/pop-cli/issues/173
3. Remove that issue from the ignore list in the`deny.toml` file. 
4. `cargo deny check advisories`  has revealed a new vulnerability in one of the dependencies. Opened an issue in the repository https://github.com/r0gue-io/pop-cli/issues/214 and included it in the ignore list in the `deny.toml` file.
=> fix: remove unused dependencies and fix cargo deny

crates/pop-cli/src/commands/build/contract.rs, crates/pop-cli/src/commands/build/mod.rs, crates/pop-cli/src/commands/build/parachain.rs, crates/pop-cli/src/commands/call/contract.rs, crates/pop-cli/src/commands/call/mod.rs, crates/pop-cli/src/commands/install/mod.rs, crates/pop-cli/src/commands/mod.rs, crates/pop-cli/src/commands/new/contract.rs, crates/pop-cli/src/commands/new/mod.rs, crates/pop-cli/src/commands/new/pallet.rs, crates/pop-cli/src/commands/new/parachain.rs, crates/pop-cli/src/commands/test/contract.rs, crates/pop-cli/src/commands/test/mod.rs, crates/pop-cli/src/commands/up/contract.rs, crates/pop-cli/src/commands/up/mod.rs, crates/pop-cli/src/commands/up/parachain.rs, crates/pop-cli/src/main.rs
Ensures all commands follow the same [`command.execute()`](https://en.wikipedia.org/wiki/Command_pattern) pattern.
Also adds some doc comments and standardises on a coding style for consistency.
=> refactor: standardise commands

Cargo.lock, Cargo.toml, crates/pop-cli/src/cli.rs, crates/pop-cli/src/commands/clean.rs, crates/pop-cli/src/commands/mod.rs, crates/pop-cli/src/main.rs, crates/pop-cli/src/style.rs
Adds a simple command which allows a user to clean the cache by selecting those cached artifacts which are no longer required.
Note: uses 'clean' so that we can potentially add a default implementation of 'pop clean' to wrap 'cargo clean'. No real benefit apart from fewer characters to type.
Closes #78
=> feat: clean cache

Cargo.toml, crates/pop-cli/src/commands/up/parachain.rs, crates/pop-parachains/src/up/chain_specs.rs, crates/pop-parachains/src/up/mod.rs, crates/pop-parachains/src/up/parachains.rs, crates/pop-parachains/src/up/relay.rs, crates/pop-parachains/src/up/sourcing.rs, crates/pop-parachains/tests/parachain.rs, tests/networks/kusama.toml, tests/networks/paseo.toml, tests/networks/polkadot+collectives.toml, tests/networks/polkadot.toml
Adds `chain-spec-generator` support, so that `pop up` can be used to launch local `paseo`, `kusama` and `polkadot` networks.
=> feat: add paseo support

crates/pop-cli/src/commands/new/parachain.rs
Reuse `cli` module functionality to standardise ux.
=> refactor: improve ux

Cargo.lock, Cargo.toml, crates/pop-cli/src/cli.rs, crates/pop-cli/src/commands/build/contract.rs, crates/pop-cli/src/commands/build/mod.rs, crates/pop-cli/src/commands/build/parachain.rs, crates/pop-cli/src/commands/mod.rs, crates/pop-cli/src/commands/up/contract.rs, crates/pop-cli/tests/parachain.rs, crates/pop-common/Cargo.toml, crates/pop-common/src/errors.rs, crates/pop-common/src/lib.rs, crates/pop-common/src/manifest.rs, crates/pop-contracts/Cargo.toml, crates/pop-contracts/src/build.rs, crates/pop-contracts/src/call.rs, crates/pop-contracts/src/errors.rs, crates/pop-contracts/src/lib.rs, crates/pop-contracts/src/up.rs, crates/pop-contracts/src/utils/helpers.rs, crates/pop-contracts/tests/contract.rs, crates/pop-parachains/src/build.rs, crates/pop-parachains/src/errors.rs, crates/pop-parachains/src/lib.rs, crates/pop-parachains/src/up/mod.rs
Enables building without needing to specify the project type - i.e. `pop b -r`
TODO:
=> feat: enable building without project type specification

crates/pop-parachains/src/up/sourcing.rs
this should fix there errs. not sure about cause, probably something related to /tmp permissions
=> fix: handle IO error if rename fails

crates/pop-contracts/src/utils/contracts_node.rs
Once the `substrate-contract-node` is downloaded, the binary is extracted to `artifacts/substrate-contracts-node-mac/substrate-contracts-node`. This made the cargo clean cache process more complex as it was failing when trying to remove the folder. 
This PR fixes that by copying the binary to the root cache folder and removing the unnecessary folders.
=> fix: remove unused folders after download contracts node binary

crates/pop-cli/src/commands/build/contract.rs, crates/pop-cli/src/commands/up/contract.rs, crates/pop-cli/src/commands/up/mod.rs, crates/pop-contracts/src/build.rs, crates/pop-contracts/src/lib.rs, crates/pop-contracts/src/up.rs, crates/pop-contracts/src/utils/contracts_node.rs, crates/pop-contracts/tests/contract.rs
Improves the ux of `pop up contract`.
=> refactor: improve up ux

crates/pop-cli/src/commands/up/contract.rs
A bug was found when running the` pop up contract`. The check to determine if the contract had been built was failing, causing the contract to be rebuilt every time.
I have added the fix and included a test to ensure this issue does not occur again.
=> fix: check if contracts needs to be build before deploy

Cargo.lock, crates/pop-cli/src/commands/test/contract.rs, crates/pop-contracts/Cargo.toml, crates/pop-contracts/src/errors.rs, crates/pop-contracts/src/lib.rs, crates/pop-contracts/src/test.rs, crates/pop-contracts/src/utils/contracts_node.rs, crates/pop-parachains/src/lib.rs, crates/pop-parachains/src/up/mod.rs, crates/pop-parachains/src/up/sourcing.rs
Refactors the usage of `substrate-contracts-node` for `pop up contract` and `pop test contract --e2e`. These now use the functionality defined in `pop-parachains` specifically for sourcing node-binaries from GitHub.
=> refactor(contracts-node): reduce duplicated code with binary sourcing

crates/pop-cli/src/commands/clean.rs, crates/pop-cli/src/commands/mod.rs
Closes #225 !
Adds a subcommand to `pop clean cache` to allow cleaning all cache artifacts at once. Useful as a shorthand!
=> feat: add `all` flag to `pop clean` 

crates/pop-cli/src/commands/build/spec.rs, crates/pop-parachains/README.md, crates/pop-parachains/src/build.rs
Handle errors for `replace_para_id`, `replace_relay_chain`, `replace_chain_type` and `replace_protocol_id` with test coverage for this new lines.
Followed the same format as we had when parsing other files: https://github.com/r0gue-io/pop-cli/blob/main/crates/pop-parachains/src/up/mod.rs#L125
Also, extended the code documentation of new logic.
=> refactor: handle errors and fix docs

crates/pop-contracts/src/up.rs
Closes https://github.com/r0gue-io/pop-cli/issues/293
=> fix: remove extra 0x in outputted text when pop up

crates/pop-cli/src/commands/new/parachain.rs, crates/pop-cli/tests/parachain.rs, crates/pop-parachains/src/templates.rs
In the `pop new parachain` command, we perform several sequential operations to gather repository information based on the user's selection:
1. Fetch the template license.
2. Retrieve latest releases to display the user the last 3.
3. Fetch commit hashes: For each of these three releases, we retrieve the commit hash associated with the specified tag in the GitHub repository.
```
◇  Select a template provider: 
│  Pop 
│
◇  Select the type of parachain:
│  Standard 
│
⚙  Template License: Unlicense
│  
◆  Select a specific release:
│  ● Polkadot v1.14 (polkadot-v.1.14.0 / 4a6e8ef)
│  ○ Polkadot v1.13 
│  ○ Polkadot v1.12 
└  
```
This process results in a total of five API calls before we even generate the parachain. If the user performs this operation twice in a short period, it results …
=> fix: limit API calls when generating parachain

Cargo.lock, Cargo.toml
This PR upgrades the `subxt` and `subxt-signer` library from version 0.35.3 to 0.37.0 and `contract-build` and `contract-extrinsic` to 5.0.0-alpha where `subxt` has been updated.
This upgrade is necessary because version 0.37 of subxt includes support for the signed extension CheckMetadataHash.
Closes the bug reported https://github.com/r0gue-io/pop-cli/issues/270
To test it you can use contract template in this branch https://github.com/r0gue-io/contracts-parachain/pull/8 or Pop Network testnet.
=> chore: bump cargo-contract and subxt versions

crates/pop-cli/src/commands/build/mod.rs, crates/pop-contracts/src/build.rs
Should enable riscv contract building.
Note that I have not been able to test due to struggling to get the `rve-nightly` toolchain installed on my system.
=> refactor(contracts): default to riscv release build

crates/pop-cli/src/commands/build/spec.rs
The spinner was not properly handled and made the output in the terminal very messy while the build was running.
Just prompting info messages should be OK for now.
Before this change whenever build spec triggers a build we get
After the changes the output doesn't mix the build prompts with the build spec command prompts
=> fix(spec): clean terminal output

crates/pop-cli/src/commands/call/contract.rs
Refactors to use the existing command state. 
- Merged `set_up_call_config` and `guide_user_to_call_contract` into a single function. 
- Also added short symbols for arguments.
=> refactor: use command state

crates/pop-common/src/git.rs, crates/pop-common/src/helpers.rs, crates/pop-common/src/lib.rs, crates/pop-common/src/polkadot_sdk.rs, crates/pop-common/src/sourcing/binary.rs, crates/pop-parachains/src/up/chain_specs.rs, crates/pop-parachains/src/up/parachains.rs, crates/pop-parachains/src/up/relay.rs
This PR addresses the sorting issue identified in: https://github.com/r0gue-io/pop-cli/issues/325 where versioned tags were prioritized over `stable2409` in the `pop up parachain` process.
- Updated the logic to use this improved sorting approach for fetching both relay and parachain binaries.
- Moved the parse_latest_tag method, which identifies the latest version by prioritizing stable-format tags, into a helper module. It was used to fetch templates, now is used for fetching relay and parachain binaries too.
=> fix: fetch stable version

crates/pop-contracts/src/new.rs, crates/pop-contracts/src/templates.rs
Closes https://github.com/r0gue-io/pop-cli/issues/323. For the contract_template's `cross-contract-calls`, it was necessary to rename `e2e_tests.rs` to match the user-defined input name. Without this adjustment, the e2e tests would fail due to the file not being correctly recognized.
Closes https://github.com/r0gue-io/pop-cli/issues/321 using the PSP34 managed by R0gue:  https://github.com/r0gue-io/PSP34
=> fix: templates errors

crates/pop-cli/src/commands/up/contract.rs, crates/pop-cli/tests/contract.rs, crates/pop-contracts/src/call.rs, crates/pop-contracts/src/node/mod.rs, crates/pop-contracts/src/up.rs
For instantiating an already uploaded contract, `code_hash` is currently not displayed, as retrieving it would require parsing events or querying the value on-chain.
It adds `-lerror,runtime::contracts=debug` when running `substrate-contracts-node` to allow debugging messages (the contract has to be build without --release flag).
=> fix: improve contract experience

crates/pop-cli/src/commands/call/contract.rs, crates/pop-contracts/src/utils/metadata.rs
Shows the full type representation, making it easier to see the entry format of parameter values.
=> refactor: format types

crates/pop-cli/src/commands/build/spec.rs
Refactor of `prepare_output_path` function to handle both directories and files passed as the output file / directory for the resulting specs.
Resolving conversation in: https://github.com/r0gue-io/pop-cli/pull/351#issuecomment-2506623640
=> chore: refactor prepare_output_path

crates/pop-cli/src/cli.rs, crates/pop-cli/src/commands/build/spec.rs, crates/pop-parachains/README.md, crates/pop-parachains/src/build.rs
Allow to provide an existing chain spec file for the `chain` flag. I aimed for flexibility and a clear flow in the code so that it is easily adaptable for future requirements.
Added an additional `BuildSpec` struct to separate the flow between getting the users input and secondary input (prompts), and generating the files with the provided options. This also allowed to not have to worry about the `Option` fields in the `BuildSpecCmd` which complicated the code. 
If the user provides a chain spec file and it does not want to make changes to it (user is prompted whether it wants this), and e.g. the para id is not present in the file, a default value is used. No warning has been added as the chance of this happening is very small. Either due to a user mistake by manually removing it or a …
=> feat: reuse existing chain spec

.github/workflows/ci.yml, crates/pop-cli/src/commands/up/contract.rs, crates/pop-cli/src/common/contracts.rs, crates/pop-cli/tests/contract.rs, crates/pop-common/src/lib.rs, crates/pop-common/src/sourcing/mod.rs, crates/pop-contracts/src/call.rs, crates/pop-contracts/src/lib.rs, crates/pop-contracts/src/node/mod.rs, crates/pop-contracts/src/testing.rs, crates/pop-contracts/src/up.rs, crates/pop-parachains/src/build.rs, crates/pop-parachains/tests/parachain.rs
This PR introduces various fixes:
1- The latest release of `substrate-contracts-node` https://github.com/paritytech/substrate-contracts-node/releases/tag/v0.42.0 introduced a new directory structure for binary extraction. This change caused `pop-cli` to fail when attempting to use the latest version. The logic has been updated to support both the old structure and the new structure.
2- The CI has been failing in the integration test `launch_paseo_and_system_parachain` due to issues with version compatibility. The test now explicitly sets the version of Paseo  to `v1.3.3` where `coretime-paseo-local` was introduced.
3- Updated CI to trigger on events like `opened`, `synchronize`, `reopened`, and `ready_for_review`, instead of only for PRs targeting `main`.
4- The function …
=> fix: support new substrate-contracts-node structure and stabilize integration tests

Cargo.lock, Cargo.toml, crates/pop-cli/src/commands/build/mod.rs, crates/pop-cli/src/commands/build/parachain.rs, crates/pop-cli/src/commands/build/spec.rs, crates/pop-cli/tests/parachain.rs, crates/pop-common/Cargo.toml, crates/pop-common/src/build.rs, crates/pop-common/src/manifest.rs, crates/pop-parachains/src/build.rs
Adds the build profile to pop cli
=> feat: production build

Cargo.lock, Cargo.toml, crates/pop-cli/src/cli.rs, crates/pop-cli/src/commands/build/mod.rs, crates/pop-cli/src/commands/build/parachain.rs, crates/pop-cli/src/commands/build/spec.rs, crates/pop-cli/src/commands/call/contract.rs, crates/pop-cli/src/commands/mod.rs, crates/pop-cli/tests/parachain.rs, crates/pop-common/Cargo.toml, crates/pop-common/src/build.rs, crates/pop-common/src/manifest.rs, crates/pop-parachains/README.md, crates/pop-parachains/src/build.rs
Fixes https://github.com/r0gue-io/pop-cli/issues/305
1. Add the flag `--chain` to specify the chain specification. Is to add this flag: https://github.com/paritytech/polkadot-sdk/blob/master/substrate/client/cli/src/params/shared_params.rs#L32 when running the `build-spec` command of the binary.
To generate `pop-node`  chain_spec mainnet for example can be done with:
`pop build spec --release --id 4024 --type live --relay paseo  --chain mainnet`
(https://github.com/r0gue-io/pop-node/blob/main/node/src/command.rs#L73)
2. As pointed in the issue the `--default-bootnode` was a bit confusing because by default was set to true and to don't  include localhost as the default bootnode has to be specified with  `--default-bootnode false`.
Set by default to false and included if specified …
=> fix: build spec experience

Cargo.lock, Cargo.toml, crates/pop-cli/src/commands/call/parachain.rs, crates/pop-parachains/src/call/metadata/mod.rs, crates/pop-parachains/src/call/metadata/params.rs, crates/pop-parachains/src/call/mod.rs, deny.toml
This PR is part of the `pop call parachain `feature. 
It improves handling the parameters with type `TypeDef::Sequence`  similar to the approach used in PolkadotJS.
1. Properly parsing user-provided values automatically encoding the value into a hexadecimal format. (Based on this comment https://github.com/r0gue-io/pop-cli/pull/316#discussion_r1874191647)
2.  Allowing users to provide large values through a file, similar to the approach used in PolkadotJS, instead of requiring direct string input:
**For testing**
Run `pop call parachain`, input a relay chain url and select the `Register a parachain ID with genesis state and code` option.
```
◇  What would you like to do?
│  Register a parachain ID with genesis state and code 
│
◇  Enter the value for the parameter: id
│  2000
│
◇  The …
```
=> feat: parse files when the argument values are very big

crates/pop-cli/src/commands/call/parachain.rs, crates/pop-common/src/metadata.rs, crates/pop-parachains/src/call/metadata/action.rs, crates/pop-parachains/src/call/metadata/mod.rs, crates/pop-parachains/src/call/metadata/params.rs, crates/pop-parachains/src/call/mod.rs
This PR is a simple refactor to address feedback from previous PRs, primarily to improve test readability:
1. Use the Default derive macro in structs. (https://github.com/r0gue-io/pop-cli/pull/363#discussion_r1875837228 and https://github.com/r0gue-io/pop-cli/pull/348#discussion_r1875734357)
2. Define constants for repeated values like URL in tests. (https://github.com/r0gue-io/pop-cli/pull/363#discussion_r1875843371)
=> refactor: use Default derive macro and define constants for test values

crates/pop-cli/src/commands/call/parachain.rs, crates/pop-parachains/src/call/mod.rs, crates/pop-parachains/src/lib.rs
This PR is part of the `pop call parachain` feature. It adds the ability to submit an extrinsic as a sudo operation using the `--sudo` flag, wrapping the selected extrinsic with sudo privileges.
_**For testing:**_
You can run `pop call parachain` interactively to select the extrinsic you want to execute and choose to run it as a sudo at the end. 
Alternatively, you can specify it directly in the command line with:
`pop call parachain --pallet System --extrinsic remark --args "0x11" --url ws://localhost:9944/ --suri //Alice --sudo`
[sc-1516]
=> feat: flag sudo to wrap extrinsic

crates/pop-cli/src/commands/call/parachain.rs, crates/pop-cli/tests/parachain.rs, crates/pop-parachains/src/call/metadata/action.rs, crates/pop-parachains/src/call/metadata/mod.rs, crates/pop-parachains/src/call/metadata/params.rs, crates/pop-parachains/src/call/mod.rs, crates/pop-parachains/src/errors.rs, crates/pop-parachains/src/lib.rs
Refactors to disambiguate between dispatchable functions and extrinsics.
=> refactor: terminology

crates/pop-cli/src/commands/call/chain.rs, crates/pop-cli/src/commands/call/mod.rs, crates/pop-cli/src/commands/call/parachain.rs, crates/pop-cli/src/commands/mod.rs, crates/pop-cli/tests/parachain.rs
Simple renaming to use `chain` instead of `parachain` as the primary command for `pop call chain` but retainining `parachain` as an alias.
Example help output:
```
Call a chain or a smart contract
Usage: pop call
pop call <COMMAND>
Commands:
chain     Call a chain [aliases: parachain]
contract  Call a contract
help      Print this message or the help of the given subcommand(s)
```
=> refactor: rename parachain with chain as the primary command and retain parachain as an alias

Cargo.lock, Cargo.toml, README.md
subxt 0.38 uses features only available from Rust 1.81: https://github.com/paritytech/subxt/commit/7d1002192e5b69947052ae8754f4e85d43d242df
=> chore: set msrv

crates/pop-cli/src/commands/build/parachain.rs, crates/pop-cli/src/commands/build/spec.rs, crates/pop-cli/src/commands/call/chain.rs, crates/pop-cli/src/commands/call/contract.rs, crates/pop-cli/src/commands/clean.rs, crates/pop-cli/src/commands/install/mod.rs, crates/pop-cli/src/commands/new/contract.rs, crates/pop-cli/src/commands/test/contract.rs, crates/pop-cli/src/commands/up/contract.rs, crates/pop-cli/src/commands/up/parachain.rs
Aligns short arg values used across commands for consistency.
=> refactor: ensure short args consistency

crates/pop-parachains/src/call/metadata/action.rs
Adds an action to make a remark, useful for testing. Also refactors the tests to simplify and fixes some incorrect language.
=> feat(call-parachain): add remark action

crates/pop-cli/src/commands/test/contract.rs, crates/pop-cli/src/commands/up/contract.rs, crates/pop-cli/src/common/contracts.rs
Improves coverage for
- `terminate_node`
- `check_contracts_node_and_prompt`
In `pop-cli/common/contracts.rs`
Refactors a few functions so that they receive the Cli as a parameter following the changes in #315  to facilitate testing.
=> test: improve coverage

crates/pop-parachains/src/up/chain_specs.rs, crates/pop-parachains/src/up/mod.rs, crates/pop-parachains/src/up/parachains.rs, crates/pop-parachains/src/up/relay.rs
Bumps the fallback versions of the relay, parachains and chain specs.
=> refactor(up): bump fallback versions

Cargo.lock, Cargo.toml, crates/pop-cli/Cargo.toml, crates/pop-cli/src/cli.rs, crates/pop-contracts/Cargo.toml, crates/pop-parachains/Cargo.toml, crates/pop-parachains/src/utils/helpers.rs
Removes a few dependencies which appear to no longer be in use. Also addresses two missed warnings.
=> build(deps): remove unused dependencies

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/pop-cli/Cargo.toml, crates/pop-cli/src/commands/build/contract.rs, crates/pop-cli/src/commands/build/mod.rs, crates/pop-cli/src/commands/build/parachain.rs, crates/pop-cli/src/commands/mod.rs, crates/pop-cli/src/commands/test/contract.rs, crates/pop-contracts/Cargo.toml, crates/pop-parachains/Cargo.toml, crates/pop-parachains/src/new_parachain.rs, crates/pop-parachains/src/templates.rs
- Remove the subcommands `parachain` and `contract` in pop build.
- Old feature to run e2e tests..
- OpenZeppelin template name changed.
_Note: In this release, a new deprecated flag has been introduced. The release flag is being deprecated in favor of profile (see [source](https://github.com/r0gue-io/pop-cli/blob/main/crates/pop-cli/src/commands/build/spec.rs#L141))._
_Note 2: Parity templates will be addressed in https://github.com/r0gue-io/pop-cli/pull/297_
=> chore: release v0.6.0

crates/pop-cli/src/common/contracts.rs, crates/pop-cli/tests/contract.rs
There was a small bug where the `skip_confirm` was ignored.
Prompting the user to source `sustrate-contracts-node`.
I have added a very minimal test. It could be improved and made more robust if we were to expand `MockCli` to include checks for certain prompts not being presented in the CLI. But that is another story.
Thanks to @ltfschoen for reporting.
[sc-2094]
=> fix: check_contracts_node handles skip_confirm

crates/pop-parachains/src/build.rs
Minor fix for the parameter type of `build_parachain`
=> docs: `profile` comment in `build_parachain`

crates/pop-cli/src/wallet_integration.rs
When attempting to register a parachain using the wallet to sign the transaction, an error appeared in the frontend:
```
Error: Unable to submit. Is the server closed?
```
This was caused by the request body limit being too low, resulting in a `413 (Payload Too Large)` error.
This PR increases DefaultBodyLimit to handle larger payloads and adds a test to verify large transaction support. The 15MB limit is a bit arbitrary but ensures stability, providing enough room for 5MB transactions while accounting for potential encoding overhead.
Resource: https://stackoverflow.com/questions/75205271/rust-axum-multipart-length-limit-exceeded.
=> fix: increase `DefaultBodyLimit` to prevent large payload failures

crates/pop-parachains/src/call/metadata/params.rs
**Context**
`pop-cli` does not support extrinsics that take another call as a parameter (e.g `Utility.batch`). Instead, when parsing the chain metadata, it returns a `FunctionNotSupported` error for such extrinsics and notifies the user that the function is not supported:
```
Select the function to call:
│  ○ as_derivative 
│  ● batch (Function Not Supported)
```
**Bug**
A bug was discovered when testing the Pop Network mainnet runtime (https://github.com/r0gue-io/pop-node/pull/448), where metadata retrieval for the Council pallet (`pallet_collective`) caused a recursion error.
The problem is because `pallet_collective` defines type `Proposal = RuntimeCall;` ([see](https://github.com/r0gue-io/pop-node/pull/448/files#diff-8dc2dbcbfe8d024a27a29dea7e603e787a48da78d1194a1cf2914b8bd4f6c635R40)) …
=> fix: prevent recursion error with `pallet_collective` metadata

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, Dockerfile, crates/pop-parachains/src/relay.rs, deny.toml
There was an issue with the CI cargo-deny tackled in the PR: https://github.com/EmbarkStudios/cargo-deny-action/issues/91
Hence, we need to update our `cargo-deny-action` to v2 to sync with the update referenced from https://github.com/restatedev/restate/commit/b16d7da8812f87cd0763e96f37519426b6c9b1f2
By updating to V2, `unmaintained = "warn"` is removed completely and all unmaintained crates now emit errors. As mentioned [here](https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html#the-version-field-optional)
Hence, reported three dependency vulnerabilities due to unmaintained crates.
- #436 
- #437 
- #438  
- #440
- #441
=> chore: update cargo-deny-action@v2

Cargo.lock, Cargo.toml, crates/pop-parachains/src/build.rs, deny.toml
After the updates in the `pop-node` release, one test was failing in the CI (https://github.com/r0gue-io/pop-cli/actions/runs/13666853327/job/38359250240?pr=435) due to a hardcoded value for the node name, `pop-devnet` which is no longer applicable in the new release. The hardcoded value has been removed. 
Additionally, this update fixes cargo deny in the CI by bumping dependency versions. It was automatic done by the [dependabot](https://github.com/apps/dependabot) https://github.com/r0gue-io/pop-cli/pull/447. But deny was still failing so had to add a vulnerability in the `deny.toml`.
The PR introduces two new vulnerability dependency: 
- #451 
- #450
=> fix: hardcoded test failing in the CI

crates/pop-cli/src/cli.rs
Add the new component password() to the `Cli` struct that enables prompt for values but masks the input. Needed for a upcoming PR.
=> chore: add password to the Cli

crates/pop-cli/src/commands/build/spec.rs, crates/pop-parachains/src/build/runtime.rs
This PR improves the process of building a deterministic runtime with two minor improvements:
- Includes the file path of the generated deterministic runtime in the list of generated files for better visibility.
- Suppresses `srtool` logs, displaying only pop logs for cleaner output.
=> chore: improve deterministic runtime flow

crates/pop-cli/src/common/wallet.rs, crates/pop-parachains/src/call/mod.rs, crates/pop-parachains/src/lib.rs
In `pop call chain`, when signing an extrinsic using `--suri`, we displayed the list of extrinsics. However, when done via `--use-wallet`, the events were not shown. This PR fixes that by reusing the same logic from `sign_and_submit_extrinsic` in `wallet::submit_extrinsic`. The only change in the code is to ensure consistency in event display.
**Output**
```
⚙  pop call chain --pallet Registrar --function reserve --url ws://127.0.0.1:54778/ --use-wallet
│  
⚙  Encoded call data: 0x4605
│  
◇  Wallet signing portal started at http://127.0.0.1:9090.
│  
◆  Signed payload received.
│  
◇  Extrinsic submitted with hash: 0x068609ed0132ae17289a3e7aa1411367b9c639e19cbee1185e4ddbbff0b3b5d4
Events
Event Balances ➜ Withdraw
who: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
amount: …
```
=> fix: display events when wallet signing

crates/pop-cli/src/commands/bench/block.rs, crates/pop-cli/src/commands/bench/machine.rs, crates/pop-cli/src/commands/bench/overhead.rs, crates/pop-cli/src/commands/bench/pallet.rs, crates/pop-cli/src/commands/bench/storage.rs, crates/pop-cli/src/common/bench.rs, crates/pop-parachains/src/bench/mod.rs, crates/pop-parachains/src/lib.rs
Overwrites the `// Executed Command:` comment block of the generated weight files. As we run the command with `omni-bencher` or `frame-benchmarking-cli`, the generated command will be something like: 
```
// Executed Command: 
//  /user/cache/pop/frame-omni-bencher
// v1
// benchmark
// pallet
// --pallet=
// --extrinsic
```
The PR will overwrites the `Executed Command` with `pop bench command`: 
```
// Executed Command: 
//  pop
//  bench
//  pallet
//  --pallet=
//  --extrinsic=
```
Another issue is with the interactive UI, we prompt user to update the command arguments. With the current weight file, it does not display the updated arguments. 
[sc-2888]
=> feat: overwrite executed command in weight files

crates/pop-cli/src/commands/mod.rs, crates/pop-cli/src/commands/test/contract.rs, crates/pop-cli/src/commands/test/mod.rs, crates/pop-common/src/errors.rs, crates/pop-common/src/lib.rs, crates/pop-common/src/test.rs, crates/pop-contracts/README.md, crates/pop-contracts/src/lib.rs, crates/pop-contracts/src/test.rs
Enables `pop test` command to run without specifying contract or chain, automatically detecting the project type. 
Previously, pop test was limited to pop test contract; now, it runs tests for all Rust projects, including chains.
**Changes**
- `test_smart_contract`(which basically wrapped `cargo test`) has been renamed to `test_project` and moved from `pop_contracts` to `pop_common` crate for broader use.
- Handles the deprecation of `pop test contract` to simple run `pop test` in your project, keeping `pop test contract`  functional for now but marking them for future removal. Following the same deprecation approach as `pop build` https://github.com/r0gue-io/pop-cli/pull/222 and `pop up` https://github.com/r0gue-io/pop-cli/pull/403 recent refactors ).
- Improved Coverage: Minor changes …
=> feat: enable `pop test` without project type specification

crates/pop-cli/src/commands/bench/block.rs, crates/pop-cli/src/commands/bench/machine.rs, crates/pop-cli/src/commands/bench/pallet.rs, crates/pop-cli/src/commands/bench/storage.rs, crates/pop-parachains/src/bench/mod.rs
Exclude custom arguments from the actual command arguments run with `frame-omni-bencher` or node binary.
=> fix: excluded custom arguments

crates/pop-cli/src/commands/bench/pallet.rs
- Add method to update the weight file template based on the feedback on #424 
- Optimize the printed command to only display arguments which are different from the default values. 
```
// Executed Command:
//  pop
//  bench
//  pallet
//  --pallet=pallet_timestamp
//  --extrinsic=
//  --steps=50
//  --output=./weights.rs
//  --runtime=/Users/chungquantin/Developer/pop-network/pop-cli/tests/runtimes/base_parachain_benchmark.wasm
//  --genesis-builder=runtime
```
=> feat: update template & optimize printed command

crates/pop-parachains/src/templates.rs
When picking templates, there was a typo in `fungible`.
=> fix: `fungible` typo in `pop new parachain` command

crates/pop-cli/src/commands/build/spec.rs
When the user doesn't want to make changes to the spec that it provides, no prompt for the default bootnode.
Closes https://github.com/r0gue-io/pop-cli/issues/444
=> fix(build spec): default bootnode prompt

crates/pop-cli/src/commands/build/spec.rs, crates/pop-parachains/src/build/mod.rs, crates/pop-parachains/src/errors.rs
This PR improves the error message when building specs fails, making it clearer and more aligned with the output of the underlying command.
**Before:**
Running `pop build spec --chain ./wrong-chain-spec`:
```
Error: IO error: command ["/templates_test/evm/target/release/parachain-template-node", "build-spec", "--chain", "./wrong-chain-spec", "--disable-default-bootnode"] exited with code 1
Caused by:
command ["templates_test/evm/target/release/parachain-template-node", "build-spec", "--chain", "./wrong-chain-spec", "--disable-default-bootnode"] exited with code 1
```
This error message was not very informative and did not clearly indicate the root cause of the failure.
**Now:**
```
Failed to build the chain spec. Error: Input("Error opening spec file `./wrong-chain-spec`: No such file or …
```
=> fix: improve build spec error messaging

Cargo.lock, crates/pop-cli/src/commands/bench/block.rs, crates/pop-cli/src/commands/bench/machine.rs, crates/pop-cli/src/commands/bench/overhead.rs, crates/pop-cli/src/commands/bench/pallet.rs, crates/pop-cli/src/commands/bench/storage.rs, crates/pop-cli/src/common/bench.rs, crates/pop-common/src/build.rs, crates/pop-parachains/src/bench/mod.rs, deny.toml
=> chore: update prompts, refactor profile variants, dim weight path description

crates/pop-cli/src/cli.rs, crates/pop-cli/src/commands/build/parachain.rs, crates/pop-cli/src/commands/build/spec.rs, crates/pop-cli/src/commands/up/mod.rs, crates/pop-cli/src/commands/up/rollup.rs, crates/pop-cli/src/deployment_api.rs, crates/pop-cli/src/style.rs, crates/pop-parachains/src/templates.rs, crates/pop-parachains/src/utils/helpers.rs
This PR introduces several UX enhancements and minor improvements gathered from the recent demo.
**Changes:**
-  Pause warning messages briefly for clarity.
- Added direct links to the Portal provider at various points in the flow.
- Improved messaging, when fetching collator keys using a spinner.
-  Prefixed `r0gue` templates for easier identification.
-  Added a `--profile` flag (default: Release) allowing users to specify the profile used when building the chain spec, reducing interactive prompts.
- User guidance: Included numbered steps throughout the flow to better assist first-time users.
=> chore: improve pop up flow

Cargo.toml, crates/pop-cli/src/commands/bench/mod.rs, crates/pop-cli/src/commands/build/mod.rs, crates/pop-cli/src/commands/build/spec.rs, crates/pop-cli/src/commands/call/contract.rs, crates/pop-cli/src/commands/call/mod.rs, crates/pop-cli/src/commands/clean.rs, crates/pop-cli/src/commands/install/mod.rs, crates/pop-cli/src/commands/mod.rs, crates/pop-cli/src/commands/new/contract.rs, crates/pop-cli/src/commands/new/mod.rs, crates/pop-cli/src/commands/new/pallet.rs, crates/pop-cli/src/commands/new/parachain.rs, crates/pop-cli/src/commands/test/contract.rs, crates/pop-cli/src/commands/test/mod.rs, crates/pop-cli/src/commands/up/contract.rs, crates/pop-cli/src/commands/up/mod.rs, crates/pop-cli/src/commands/up/network.rs, crates/pop-cli/src/common/mod.rs, crates/pop-cli/src/main.rs, crates/pop-telemetry/src/lib.rs
Refactors the implementations for collecting events and data from executing commands.
Essentially we convert the command before it is executed in the primary event. After execution the cli returns additional data. When an error occurs the error is added as data.
=> feat: canonical command names

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/pop-cli/Cargo.toml, crates/pop-cli/src/commands/build/spec.rs, crates/pop-contracts/Cargo.toml, crates/pop-parachains/Cargo.toml
- Remove the subcommands `release` flag in `pop build spec` command.
Wait until this https://github.com/r0gue-io/pop-cli/pull/497 is merged to include improvements in telemetry in the release.
=> chore: release v0.7.0

Cargo.lock, crates/pop-cli/src/commands/bench/overhead.rs, crates/pop-cli/src/commands/bench/pallet.rs, crates/pop-cli/src/commands/build/mod.rs, crates/pop-cli/src/commands/build/parachain.rs, crates/pop-cli/src/commands/build/runtime.rs, crates/pop-cli/src/commands/build/spec.rs, crates/pop-cli/src/common/runtime.rs, crates/pop-cli/src/common/try_runtime.rs, crates/pop-common/src/manifest.rs, crates/pop-parachains/src/build/runtime.rs, crates/pop-parachains/src/lib.rs
- The PR implements a feature to build only the runtime when the user is in the `/runtime` folder of the parachain project. Tackling the issue #504. 
- Implements `pop build --deterministic` to build a runtime deterministically. #478 
- If `--only-runtime` is provided and the command is run at the parachain project root, it prompts user to select the runtime to build if there're multiple. If there is only one runtime, it builds the runtime instead of a parachain. 
```
pop build --only-runtime
```
Or
```
pop build --deterministic --only-runtime
```
=> feat: `pop build runtime` and `pop build --deterministic`

Cargo.lock, crates/pop-cli/src/common/bench.rs, crates/pop-cli/src/common/binary.rs, crates/pop-cli/src/common/try_runtime.rs
- Add a new type `SemanticVersion` to represent to the semantic version `(minor, major, patch)`
- Add a new method `which_version` that returns the path to the binary if the version matches the targeted one.
=> chore: source remote binary if version not matches

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, crates/pop-cli/Cargo.toml, crates/pop-cli/src/cli.rs, crates/pop-cli/src/commands/bench/block.rs, crates/pop-cli/src/commands/bench/machine.rs, crates/pop-cli/src/commands/bench/overhead.rs, crates/pop-cli/src/commands/bench/storage.rs, crates/pop-cli/src/commands/build/mod.rs, crates/pop-cli/src/commands/build/runtime.rs, crates/pop-cli/src/commands/mod.rs, crates/pop-cli/src/commands/test/execute_block.rs, crates/pop-cli/src/commands/test/fast_forward.rs, crates/pop-cli/src/commands/test/mod.rs, crates/pop-cli/src/commands/test/on_runtime_upgrade.rs, crates/pop-cli/src/common/binary.rs, crates/pop-cli/src/common/builds.rs, crates/pop-cli/src/common/mod.rs, crates/pop-cli/src/common/prompt.rs, crates/pop-cli/src/common/try_runtime.rs, crates/pop-cli/src/common/wallet.rs, crates/pop-cli/src/main.rs, crates/pop-cli/src/style.rs, crates/pop-parachains/src/bench/mod.rs, crates/pop-parachains/src/lib.rs, crates/pop-parachains/src/try_runtime/mod.rs
Eliminates unnecessary dependencies when building without default features. The number of dependencies when building with the `contract` feature only has been halved from ~1k to 500k. A handful were removed more generally by using `default-features = false`.
Also updates CI to ensure that builds with -`-no-default-features` are successful and remain so. Whilst the tool is primarily aimed towards contract and parachain development, allowing successful builds with no default features allows the introduction and testing of additional experimental features which are not specific to these two developer journeys.
[sc-3569]
=> build(deps): eliminate unnecessary dependencies

crates/pop-cli/src/common/bench.rs, crates/pop-cli/src/common/try_runtime.rs, crates/pop-parachains/src/bench/binary.rs
Update the version tests of the binaries `frame-omni-bencher` and `try-runtime`. The idea is, whatever versions above the threshold one are accepted and source binaries if the deprecated version of the binaries used.
If there is a break in the future version of the binary, we update the threshold version and change the code to support newer versions.
=> chore: update required version of the frame-omni-bencher binary

Cargo.toml, crates/pop-cli/Cargo.toml, crates/pop-cli/src/commands/hash.rs, crates/pop-cli/src/commands/mod.rs
Based on https://www.shawntabrizi.com/substrate-js-utilities/ and https://github.com/hack-ink/subalfred, adds a simple `hash` command as an additional utility to the CLI. It is feature gated behind `experimental` for now. It supports all the hashers typically used by the SDK (blake2, keccack, sha2, twox), without taking on any new dependencies.
```shell
cargo install --path ./crates/pop-cli --locked --features experimental
```
There is a subcommand for each supported hasher, which expects the required length of the output along with input data in the form of a string, hex or path to a file to be hashed. The command structure is intended to be as simple as possible, whilst also allowing easier future extensibility. Whilst the commands could be combined with the output length (e.g. …
=> feat: hashing

.github/actions/init/action.yml
Noticed some caching issues in the CI runs due to sunsetting of old GitHub cache actions (https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/#decommissioned-cache-service-brownouts), so updating to the latest version of the rust-cache action.
Also clears additional space.
=> ci: update init to use latest rust-cache action

Cargo.lock, Cargo.toml, README.md, crates/pop-common/Cargo.toml, crates/pop-common/src/api.rs, crates/pop-common/src/git.rs, crates/pop-common/src/lib.rs, crates/pop-common/src/sourcing/mod.rs
Applies some of the best practices from https://docs.github.com/en/rest/using-the-rest-api/best-practices-for-using-the-rest-api in an attempt to minimize errors caused by rate limiting of the Github API. When rate limiting occurs, errors will be returned with more detail information.
One can also now create a personal token on GitHub and specify locally via `GITHUB_TOKEN` if rate limiting occurs. The default limit is 60 per hour, so probably fine for most standard CLI usage.
todos:
[sc-3686]
=> fix: wrap github rest api access in an apiclient

crates/pop-cli/src/commands/bench/overhead.rs, crates/pop-cli/src/commands/bench/pallet.rs, crates/pop-cli/src/commands/build/runtime.rs, crates/pop-cli/src/common/runtime.rs, crates/pop-cli/src/common/try_runtime.rs
Closes #519 
- Instead of returning the path to the runtime WASM binary `.wasm`, we return the runtime project path. For example, if `pop-node/runtime/testnet` is selected or inputted, it is returned in the single command output or the `.bench` file as: `--runtime=pop-node/runtime/testnet`. Then when running the command, runtime project can be located and rebuilt. If `.wasm` file is provided, the build process is skipped. 
- Output the relative path of the runtime project in `.bench` file and the single command output
```
runtime = "/Users/chungquantin/Developer/pop-network/pop-node/target/release/wbuild/pop-runtime-testnet/pop_runtime_testnet.wasm"
```
```
runtime = "/Users/chungquantin/Developer/pop-network/pop-node/runtime/testnet"
```
- Go to `pop-node`
- Run the command `pop bench …
=> fix: separate runtime binary path and project path

crates/pop-parachains/src/bench/mod.rs, rust-toolchain.toml
Fixes the current failing test by updating the expected value.
=> test(parachains/bench): fix expected error in load_pallet_extrinsics test

.github/workflows/ci.yml
The polkavm contract jobs are currently running all tests in the project rather than only those which actually have the specified features. That is, parachain jobs are being run in parallel unnecessarily.
This PR simply constrains these jobs to only run over the `pop-cli` and `pop-contracts` crates where these features exist.
=> ci: optimize polkavm contract jobs

crates/pop-cli/src/common/try_runtime.rs
The list of pallets on the live network changed recently, causing a try-state test to fail. 
Ideally that test should be rewritten to run against a local node/mock, but that it beyond the current requirements to fix CI, which is preventing other PRs from being merged.
[sc-3794]
=> test(cli/try-runtime): update pallets in try-state test after runtime upgrade

Dockerfile
This PR updates the Dockerfile to replace the runtime base image `rust:slim` with `ubuntu:24.04`. This resolves runtime errors caused by incompatible `glibc` versions when running the pop up network https://github.com/r0gue-io/pop-cli/issues/401
[sc-3871]
=> fix(dockerfile): could not launch local network

crates/pop-parachains/src/lib.rs, crates/pop-parachains/src/registry/mod.rs, crates/pop-parachains/src/registry/system.rs, crates/pop-parachains/src/up/mod.rs
This PR enables running the `passet-hub` locally alongside `asset-hub` using the following command:
```
cargo run up paseo -p asset-hub,passet-hub
pop up paseo -p asset-hub,passet-hub
```
- This is a temporary workaround: the chain spec for `passet-hub` is currently hardcoded in the repository `artifacts/passet-hub-spec.json` for the hackathon.
- Future changes required will be minimal after the chain spec generator update. Once [support for PassetHub is integrated into the paseo chain spec generator](https://github.com/paseo-network/passet-hub/compare/al3mart/chore-spec-generator?expand=1), we can remove the .json file and the associated TODOs.
=> feat: launch passet hub locally

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/pop-chains/Cargo.toml, crates/pop-cli/Cargo.toml, crates/pop-contracts/Cargo.toml
- Bump all crate versions to `0.9.0`.
- Updated Changelog file with` git cliff --bump`.
After this PR is merge:
=> chore: release0.9.0

.github/workflows/ci.yml, crates/pop-cli/Cargo.toml, crates/pop-cli/src/cli.rs, crates/pop-cli/src/commands/hash.rs, crates/pop-cli/src/commands/mod.rs
This PR:
- Removes the `experimental` and `hashing` features.
- Uses plain output in the hashing command.
- Removes the leading `0x` from the output.
=> chore: Improve the hashing command

crates/pop-cli/src/cli.rs, crates/pop-cli/src/commands/call/contract.rs
Closes #561
This PR enhances the contract call command by storing the contract path in subsequent calls to the same contract. 
Since I was on it, I slightly improved the error message in the mocked cli in case a given message, identified by its index, is not found.
=> Skip redundant question when calling a contract

crates/pop-cli/src/cli.rs, crates/pop-cli/src/commands/call/contract.rs
Closes #611
This PR showcases those operations in smart contracts that imply sending an extrinsic from those that merely read from the storage.
=> feat(cli): clearly highlight writing operations when calling smart contracts

crates/pop-cli/src/commands/call/chain.rs
Closes #610
This PR avoids asking every time to the user wether the call should be run with sudo or not.
Instead, it simply asks the user to confirm its decision if the `--root` flag is specified.
Example:
=> feat(cli): do not ask to run with sudo for every call

crates/pop-cli/src/commands/call/contract.rs, crates/pop-cli/src/commands/up/contract.rs, crates/pop-cli/src/common/contracts.rs, crates/pop-contracts/src/lib.rs
This PR improves the handling of user-provided arguments for contract calls:
- Strings: User input is automatically normalized to ensure values are wrapped in double quotes (if not already).
Closes https://github.com/r0gue-io/pop-cli/issues/408
- None values: User input "None" is automatically normalized to an empty string ("").
Closes https://github.com/r0gue-io/pop-cli/issues/579
=> fix: process user input for Strings and None values

.github/workflows/ci.yml, README.md
Remove the `deny` job from CI: it’s producing frequent  failures due to new upstream advisories on transitive deps, even when none new dependency has been added.
I keep `deny.toml` in the repo for local checks and future re-enablement with a quick explanation on how to use it in the README.
=> chore: remove cargo deny job from the CI

crates/pop-cli/src/commands/install/mod.rs
Closes https://github.com/r0gue-io/pop-cli/issues/568
Update the packages needed to be installed from the official Polkadot docs: [https://docs.polkadot.com/develop/parachains/install-polkadot-sdk](https://docs.polkadot.com/develop/parachains/install-polkadot-sdk) replacing the ones we used before from and old documentation page https://docs.substrate.io/install/
=> chore(pop install): update packages to be installed

.github/workflows/ci.yml, .github/workflows/coverage.yml, .github/workflows/integration-tests.yml
This PR:
- Moves integration tests to a separate workflow.
- ~~Does not optimize disk space in the coverage workflow, as it is no longer needed due to the smaller disk consumption.~~ Actually never mind. It is required to optimize 😓 (see the [failing job](https://github.com/r0gue-io/pop-cli/actions/runs/18286064534)).
- Display more output in tests.
- Updates cache names in case builds are performed with different rust flags or OS.
=> ci: optimize ci integration tests

crates/pop-cli/src/commands/up/contract.rs, crates/pop-cli/src/commands/up/mod.rs
Closes #623.
This PR adds a `skip-build` command to `pop up contract`.
- If `false`, it will always rebuild the contract, even if it was already built. This is the default behaviour.
- If `true`, it won't build the contract in advance, UNLESS it wasn't built already. If so, it'll be built, ignoring the `--skip-build` flag.
=> feat: always build contracts with pop up

codecov.yml
For the coverage CI mark the project and patch checks as informational instead of showing it red  in the CI.
An example on how it works in this PR: https://github.com/r0gue-io/pop-cli/pull/567 where I merged this change
=> chore(ci): mark coverage status project and patch as informational only
